import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.js';
import {
  fetchAlerts,
  exportAlertsReport,
  type Alert,
  type AlertFilterParams,
  type AlertsResponse,
  type SeverityLevel,
  type AlertStatus,
} from '../api/alerts.js';
import Pagination from '../components/Pagination.js';

const SEVERITIES: Array<{ value: SeverityLevel; label: string; badgeCls: string }> = [
  { value: 'critical', label: 'Critical', badgeCls: 'border-severity-critical text-severity-critical' },
  { value: 'high', label: 'High', badgeCls: 'border-severity-high text-severity-high' },
  { value: 'medium', label: 'Medium', badgeCls: 'border-severity-medium text-severity-medium' },
  { value: 'low', label: 'Low', badgeCls: 'border-severity-low text-severity-low' },
];

const STATUSES: Array<{ value: AlertStatus; label: string; badgeCls: string }> = [
  { value: 'new', label: 'New', badgeCls: 'border-accent-primary text-accent-primary bg-accent-primary/10' },
  { value: 'investigating', label: 'Investigating', badgeCls: 'border-severity-high text-severity-high bg-severity-high/10' },
  { value: 'resolved', label: 'Resolved', badgeCls: 'border-severity-resolved text-severity-resolved bg-severity-resolved/10' },
  { value: 'false_positive', label: 'False Positive', badgeCls: 'border-text-disabled text-text-secondary bg-bg-surface-raised' },
];

const PAGE_SIZE = 50;

export default function AlertFeed() {
  const { authFetch } = useAuth();
  const navigate = useNavigate();

  // Filters
  const [severity, setSeverity] = useState<SeverityLevel | ''>('');
  const [status, setStatus] = useState<AlertStatus | ''>('');
  const [sourceIp, setSourceIp] = useState('');
  const [mitreId, setMitreId] = useState('');

  // Results
  const [result, setResult] = useState<AlertsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const getFilterParams = useCallback((): AlertFilterParams => {
    const params: AlertFilterParams = {};
    if (severity) params.severity = severity;
    if (status) params.status = status;
    if (sourceIp.trim()) params.sourceIp = sourceIp.trim();
    if (mitreId.trim()) params.mitreId = mitreId.trim();
    return params;
  }, [severity, status, sourceIp, mitreId]);

  const doSearch = useCallback(
    async (page: number = 1) => {
      setLoading(true);
      setError(null);
      try {
        const params = getFilterParams();
        params.page = page;
        params.pageSize = PAGE_SIZE;

        const data = await fetchAlerts(authFetch, params);
        setResult(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to fetch alerts');
      } finally {
        setLoading(false);
      }
    },
    [authFetch, getFilterParams],
  );

  useEffect(() => {
    doSearch(1);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleExport(format: 'csv' | 'json') {
    setExporting(true);
    try {
      await exportAlertsReport(authFetch, getFilterParams(), format);
    } catch (err) {
      window.alert(err instanceof Error ? err.message : 'Report export failed');
    } finally {
      setExporting(false);
    }
  }

  function handleFilter(e: React.FormEvent) {
    e.preventDefault();
    doSearch(1);
  }

  function handleReset() {
    setSeverity('');
    setStatus('');
    setSourceIp('');
    setMitreId('');
  }

  function formatTimestamp(ts: string): string {
    try {
      return new Date(ts).toLocaleString('en-GB', {
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
        hour12: false,
      });
    } catch {
      return ts;
    }
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-text-primary">Alert Feed</h1>
          <p className="mt-1 text-sm text-text-secondary">
            Monitor and triage security detection alerts generated by the rule engine.
          </p>
        </div>

        {/* Export Report Actions */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => handleExport('csv')}
            disabled={exporting}
            className="flex items-center gap-1.5 rounded border border-border-default bg-bg-surface px-3 py-1.5 text-xs text-text-primary transition-colors hover:bg-bg-surface-raised disabled:opacity-50"
          >
            <span>📄</span>
            <span>{exporting ? 'Exporting…' : 'Export CSV'}</span>
          </button>
          <button
            onClick={() => handleExport('json')}
            disabled={exporting}
            className="flex items-center gap-1.5 rounded border border-border-default bg-bg-surface px-3 py-1.5 text-xs text-text-primary transition-colors hover:bg-bg-surface-raised disabled:opacity-50"
          >
            <span>{'{ }'}</span>
            <span>{exporting ? 'Exporting…' : 'Export JSON'}</span>
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <form
        onSubmit={handleFilter}
        className="mb-6 rounded-card border border-border-default bg-bg-surface p-4"
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {/* Severity */}
          <div>
            <label className="mb-1 block text-xs text-text-secondary">Severity</label>
            <select
              value={severity}
              onChange={(e) => setSeverity(e.target.value as SeverityLevel | '')}
              className="w-full rounded border border-border-default bg-bg-base px-3 py-2 text-xs text-text-primary focus:border-accent-primary focus:outline-none"
            >
              <option value="">All Severities</option>
              {SEVERITIES.map((s) => (
                <option key={s.value} value={s.value}>
                  {s.label}
                </option>
              ))}
            </select>
          </div>

          {/* Status */}
          <div>
            <label className="mb-1 block text-xs text-text-secondary">Status</label>
            <select
              value={status}
              onChange={(e) => setStatus(e.target.value as AlertStatus | '')}
              className="w-full rounded border border-border-default bg-bg-base px-3 py-2 text-xs text-text-primary focus:border-accent-primary focus:outline-none"
            >
              <option value="">All Statuses</option>
              {STATUSES.map((st) => (
                <option key={st.value} value={st.value}>
                  {st.label}
                </option>
              ))}
            </select>
          </div>

          {/* Source IP */}
          <div>
            <label className="mb-1 block text-xs text-text-secondary">Source IP</label>
            <input
              type="text"
              value={sourceIp}
              onChange={(e) => setSourceIp(e.target.value)}
              placeholder="e.g. 192.168.1.105"
              className="w-full rounded border border-border-default bg-bg-base px-3 py-2 font-mono text-xs text-text-primary placeholder:text-text-disabled focus:border-accent-primary focus:outline-none"
            />
          </div>

          {/* MITRE ID */}
          <div>
            <label className="mb-1 block text-xs text-text-secondary">MITRE Technique ID</label>
            <input
              type="text"
              value={mitreId}
              onChange={(e) => setMitreId(e.target.value)}
              placeholder="e.g. T1110"
              className="w-full rounded border border-border-default bg-bg-base px-3 py-2 font-mono text-xs text-text-primary placeholder:text-text-disabled focus:border-accent-primary focus:outline-none"
            />
          </div>
        </div>

        <div className="mt-4 flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={handleReset}
            className="rounded border border-border-default px-3 py-1.5 text-xs text-text-secondary hover:bg-bg-surface-raised"
          >
            Reset
          </button>
          <button
            type="submit"
            disabled={loading}
            className="rounded bg-accent-primary px-4 py-1.5 text-xs font-semibold text-bg-base transition-opacity disabled:opacity-50"
          >
            {loading ? 'Filtering…' : 'Apply Filters'}
          </button>
        </div>
      </form>

      {error && (
        <div className="mb-4 rounded border border-severity-critical/30 bg-severity-critical/5 px-4 py-3 text-sm text-severity-critical">
          {error}
        </div>
      )}

      {loading && !result ? (
        <div className="flex items-center justify-center py-20">
          <div className="h-6 w-6 animate-spin rounded-full border-2 border-accent-primary border-t-transparent" />
        </div>
      ) : result && result.alerts.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-card border border-border-default bg-bg-surface py-20">
          <div className="mb-4 text-4xl opacity-30">⚠</div>
          <h3 className="text-sm font-semibold text-text-primary">No alerts found</h3>
          <p className="mt-1 text-xs text-text-secondary">
            No alerts match your filter criteria.
          </p>
        </div>
      ) : result ? (
        <>
          <div className="mb-3 flex items-center justify-between text-xs text-text-secondary">
            <span>
              Showing {(result.page - 1) * result.pageSize + 1}–
              {Math.min(result.page * result.pageSize, result.total)} of{' '}
              <span className="font-mono text-text-primary">{result.total.toLocaleString()}</span> alerts
            </span>
          </div>

          <div className="overflow-x-auto rounded-card border border-border-default">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-border-default bg-bg-surface text-text-secondary">
                  <th className="px-4 py-3 font-medium">Severity</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Rule Name</th>
                  <th className="px-4 py-3 font-medium">Source IP</th>
                  <th className="px-4 py-3 font-medium">MITRE ID</th>
                  <th className="px-4 py-3 font-medium">Triggered At</th>
                  <th className="px-4 py-3 font-medium">Assigned To</th>
                </tr>
              </thead>
              <tbody>
                {result.alerts.map((alert: Alert) => {
                  const sevInfo = SEVERITIES.find((s) => s.value === alert.severity);
                  const stInfo = STATUSES.find((s) => s.value === alert.status);
                  return (
                    <tr
                      key={alert.id}
                      onClick={() => navigate(`/alerts/${alert.id}`)}
                      className={`cursor-pointer border-b border-border-default bg-bg-surface transition-colors hover:bg-bg-surface-raised ${
                        alert.severity === 'critical'
                          ? 'severity-rail border-l-severity-critical'
                          : alert.severity === 'high'
                            ? 'severity-rail border-l-severity-high'
                            : alert.severity === 'medium'
                              ? 'severity-rail border-l-severity-medium'
                              : 'severity-rail border-l-severity-low'
                      }`}
                      style={{ minHeight: '44px' }}
                    >
                      {/* Severity */}
                      <td className="whitespace-nowrap px-4 py-3">
                        <span className={`severity-rail ${sevInfo?.badgeCls} rounded bg-bg-surface-raised px-2 py-0.5 font-mono text-[11px]`}>
                          {sevInfo?.label ?? alert.severity}
                        </span>
                      </td>

                      {/* Status */}
                      <td className="whitespace-nowrap px-4 py-3">
                        <span className={`rounded border px-2 py-0.5 font-mono text-[11px] ${stInfo?.badgeCls}`}>
                          {stInfo?.label ?? alert.status}
                        </span>
                      </td>

                      {/* Rule Name */}
                      <td className="px-4 py-3 font-semibold text-text-primary">
                        {alert.rule_name}
                      </td>

                      {/* Source IP */}
                      <td className="whitespace-nowrap px-4 py-3 font-mono text-text-primary">
                        {alert.source_ip}
                      </td>

                      {/* MITRE ID */}
                      <td className="whitespace-nowrap px-4 py-3 font-mono text-accent-primary">
                        {alert.mitre_technique_id ?? '—'}
                      </td>

                      {/* Triggered At */}
                      <td className="whitespace-nowrap px-4 py-3 font-mono text-text-secondary">
                        {formatTimestamp(alert.created_at)}
                      </td>

                      {/* Assigned Analyst */}
                      <td className="whitespace-nowrap px-4 py-3 text-text-secondary">
                        {alert.assigned_to_email ?? 'Unassigned'}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <Pagination
            page={result.page}
            totalPages={result.totalPages}
            onPageChange={(p) => doSearch(p)}
          />
        </>
      ) : null}
    </div>
  );
}
